maridb:
	docker run  --name FahmiDB -p 192.168.100.23:3306:3306   --env MARIADB_ROOT_PASSWORD=tes  -d mariadb:latest
iscoop:
	Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
imigrate:
	scoop install migrate
sqlc:
sqlc generate

.